README.md
lib/bin.js
lib/dir.js
lib/fetcher.js
lib/file.js
lib/git.js
lib/registry.js
tap-snapshots/test-bin.js-TAP.test.js
tap-snapshots/test-dir.js-TAP.test.js
tap-snapshots/test-fetcher.js-TAP.test.js
tap-snapshots/test-fetcher.js-fake-sudo-TAP.test.js
tap-snapshots/test-file.js-TAP.test.js
tap-snapshots/test-index.js-TAP.test.js
tap-snapshots/test-remote.js-TAP.test.js
test/bin.js
test/git.js
test/registry.js

While this is a bit redundant, given the fact that whoever is calling
pacote already knows this by definition, it's also a huge pain to track
when kicking off a ton of requests in parallel.  Much better to just
return it at the end of the process as well, to save the caller that
reassembly and bookkeeping.

Return the requested spec as the 'from' value

---

lib/util/git.js
test/git.cwd-owner.js

Fix: https://github.com/npm/cli/issues/624
Infer the ownership of a git command invocation based on the cwd, if one is
specified.

fix(git): Do not drop uid/gid when executing in root-owned directory

---

.github/settings.yml
.github/workflows/ci.yml
.gitignore
README.md
lib/fetcher.js
lib/registry.js
lib/remote.js
lib/util/git/spawn.js
package-lock.json
package.json
test/dir.js
test/remote.js
test/util/git/spawn.js

Depends on https://github.com/npm/npm-registry-fetch/pull/25
Land that PR before merging this commit.

update to referer-less npm-registry-fetch

---

lib/fetcher.js
lib/remote.js
tap-snapshots/test-remote.js-TAP.test.js
test/fetcher.js
test/remote.js

There are a few places in npm where we treat the default registry url
https://registry.npmjs.org as a "Magic String", which always indicates
that the configured registry should be used.
This is important, because it means that lockfiles which are generated
while talking to one registry do not result in fetching from a different
registry to install their packages.  It also means that proxies which do
not rewrite the dist.tarball URLs will still effectively proxy, which is
often required in bastion-type networking setups.
NB: the *inverse* (ie, saving requests to alternative registries in
lockfiles and package.json files as https://registry.npmjs.org URLs) is
*not* done, as it could result in leaking the package names of private
code via requests to the main registry.
The missing piece in …

Consistently treat default registry as magic string

---

lib/fetcher.js

**What / Why**
I am getting this error on my Jenkins docker build:
```
TypeError: Cannot read property 'then' of null
at /home/jenkins/agent/workspace/<project>/node_modules/pacote/lib/fetcher.js:355:13
```
This is because the return value of `this[_chown]` is `null`, and not a `Promise` as the `tarballFile()` logic assumes.
```javascript
[_chown] (path, uid, gid) {
return selfOwner && (selfOwner.gid !== gid || selfOwner.uid !== uid)
? chownr(path, uid, gid)
: /* istanbul ignore next - we don't test in root-owned folders */ null
}
```
This PR attempts to simply add a null check and otherwise maintain behavior. I've tested this issue with an internal build, and verified it resolves the issue.

Prevent null TypeError using Pacote.tarball.file() as root on unix machines

---

README.md
lib/fetcher.js
lib/registry.js
test/registry.js

This allows us to avoid hitting the registry repeatedly to get the same
packument multiple times when we are resolving many different specifiers
for the same package name.
Even though these requests are cached after the first hit, just pinging
the registry with an ETag and getting a 304 response still adds up to
quite a bit of time waiting on network requests to complete.

Add packumentCache option

---

lib/fetcher.js
lib/git.js
lib/util/cache-dir.js
lib/util/npm.js
tap-snapshots/test-util-npm.js-TAP.test.js
test/fetcher.js
test/git.js
test/util/cache-dir.js
test/util/npm.js

Prevent infinite recursion in git dep preparation
When a git spec is installed, we clone the repo and run 'npm install' if
it has a prepare script, so that the correct bits get loaded.
If one of its dependencies is also a git spec, we do the same thing for
that dependency.
If the dependency graph loops back on itself, we're in trouble.
The solution here is to track the path of git prepare steps we've
followed, and bail out of it when a cycle is detected.  This MAY result
in a package dependency not being fully built, and if that git dep's
preparation is required for the dependent to properly be installed, oh
well, that's going to break.
But what it WON'T do is create an infinitely deep tree of processes
calling npm and git recursively without end until the user SIGINTs out
of it.
See: …

Prevent infinite recursion in git dep preparation

---

README.md
lib/dir.js
lib/index.js
lib/util/tar-create-options.js
test/dir.js
test/index.js
test/util/tar-create-options.js

Exposes `tar.c` options as a helper util. Useful for other apps that
might want to replicate the same tarball creation from the npm cli in
different contexts.
Related to: https://github.com/npm/libnpmdiff/pull/3

feat: exposes tar create options

---

lib/util/tar-create-options.js
tap-snapshots/test-dir.js-TAP.test.js
test/dir.js
test/util/tar-create-options.js

this seems to avoid some platform related optimizations that result in integrity mismatches due to the resulting compressed output not being byte for byte identical.
it's a band-aid, but it did allow me to get the same end result in both arm and intel builds of node on my m1 mbp.
tested and found same results in:
Closes https://github.com/npm/cli/issues/2846

fix: force gzip compression level to 9

---

lib/registry.js
test/registry.js

Other manifest code paths go through read-package-json-fast, which end
up normalized through that package's `normalize` function.  Manifests
picked from the registry do not.  This adds consistency between the two.
Fixes https://github.com/npm/cli/issues/3132

fix(registry): normalize registry manifests

---

lib/fetcher.js
tap-snapshots/test/fetcher.js-fake-sudo.test.cjs
tap-snapshots/test/fetcher.js.test.cjs

fix: include all dep types when building for prepare

---

lib/git.js
test/git.js

This rethrows git pathspec errors early since there is no point in retrying them.
In `_resolvedFromHosted` the benefit is that resolving doesn't need to be attempted again.
In `_cloneHosted` prior to this change, retrying a missing pathspec would change the error to something like `fatal: destination path '/Users/lukekarrys/.npm/_cacache/tmp/git-clone-e421e02b/.git' already exists and is not an empty directory.` which was obscuring the actual error.
With this change, this is what the error looks like in the cli:
**Old**
**New**
Ref: https://github.com/npm/cli/issues/3149

rethrow git pathspec errors from git operations on hosted services

---

.github/workflows/ci.yml
package.json

BREAKING CHANGE: this moves our `engines` support and testing matrix
forward to node12 LTS and above.

fix: drop node 10 support

---

lib/git.js
test/git.js

Draft until I write tests for this
This change will reify a git dependency if that git dependency has workspaces defined.
This is necessary because for git dependencies on a known hosting provider, we actually download an archive file rather than cloning the repository. That's all well and good, but `tar` refuses to unpack symlinks which is how a workspace tends to be stored in `node_modules` in a git repository that happens to have `node_modules` checked in. The end result today is that `npm i -g npm/cli#release-next` gives you a broken installation because all of the workspace modules are missing.
We could potentially extend the check so that it requires that the workspaces are defined _and_ bundled dependencies are in use _and_ a node_modules directory is present to be as specific as …

fix: reify git dependencies that have workspaces

---

lib/git.js
test/git.js

When running prepare steps for git dependencies, we should also check
for `prepack` scripts and make sure the prepare steps are run in case
one is found.
Fixes: https://github.com/npm/cli/issues/4391

fix: run prepack lifecycle scripts on git fetcher

---

lib/bin.js
lib/util/trailing-slashes.js
tap-snapshots/test/dir.js.test.cjs
test/fixtures/abbrev/abbrev.js

.substr() is deprecated so we replace it with .slice() which works similarily but isn't deprecated
Credit: Tobias Speicher <rootcommander@gmail.com>

fix: replace deprecated String.prototype.substr()

---

lib/fetcher.js
lib/remote.js
package.json
test/fetcher.js
test/fixtures/tnock.js
test/registry.js

By default, a package manifest might contain dist tarballs with "registry.npmjs.org" hosts, which will be replaced automatically with the configured registry host.
This PR adds an option, `replaceRegistryHost`, which is `true` by default.
When set to `false`, "registry.npmjs.org" is no longer treated like a magic value.

feat: add option to not replace magic registry host

---

lib/fetcher.js
lib/remote.js
test/fetcher.js
test/remote.js

The pacote option `replaceRegistryHost` currently supports values "npmjs" (default) and "never".
This PR adds "always". When "always" is set, the registry host in the tarball url of the packument is always replaced with the current `registry`, regardless of its packument reference value.

feat: add always option to replaceRegistryHost

---

lib/dir.js

this sets us up for changes to the cli itself and npm-packlist that will ensure we respect .gitignore and .npmignore files from a workspace root when we're packing a workspace

fix: pass prefix and workspaces to npm-packlist

---

package.json

this raises the npm-packlist dependency to the required version to allow for workspace awareness. the necessary change here was made in #173

feat: bump npm-packlist for workspace awareness

---

lib/fetcher.js
lib/remote.js
test/fetcher.js
test/registry.js

Feedback from adding this feature to the main CLI lead to the idea that this value could be a host, rather than an enum of ('npmjs', 'always', 'never').
Now the valid values are ('npmjs', 'always', 'never', <hostname>). 'npmjs' is now an alias to 'registry.npmjs.org'

feat: replaceRegistryHost can now be a hostname

---

README.md

Does it make sense to add the manifest [`_id`](https://github.com/npm/read-package-json-fast#:~:text=set%20the%20_id%20property%20if%20name%20and%20version%20are%20set.%20(this%20is%20load-bearing%20in%20a%20few%20places%20within%20the%20npm%20cli.)) field and the packument [`_cached` and `_contentLength`](https://github.com/npm/pacote/blob/298df450c03af17c069b8e40834d0154e801b61e/lib/registry.js#L77-L78) fields to the README, along with the other fields that Pacote adds? That's what this PR does.

docs: add some fields to the README

---

README.md
lib/registry.js

I'm interested in telling whether the result of `pacote.manifest()` came from the registry or from the cacache. Is that what the existing packument `_cached` field indicates? https://github.com/npm/pacote/blob/298df450c03af17c069b8e40834d0154e801b61e/lib/registry.js#L77
If so, does it make sense to add that field to `pacote.manifest()` results, and is this PR the correct way/location to do it?

fix(packument): eliminate _cached field

---

lib/dir.js
lib/fetcher.js
package.json
test/dir.js
test/fixtures/npm-mock.js
test/git.js

If a tree is not passed in, then pacote will create one with
`loadActual` and the resolved path to the directory it is preparing.
BREAKING CHANGE: `pacote` now has a peer dependency on
`@npmcli/arborist`.

feat: pacote now optionally takes a tree when preparing directories

---

lib/dir.js
lib/fetcher.js
lib/git.js
package.json
test/dir.js
test/fixtures/npm-mock.js
test/git.js

This reverts the peer dependency change from d3517fd.
BREAKING CHANGE: a `@npmcli/arborist` constructor must be passed in if
no tree is provided and pacote is going to operate on git dependencies.

feat: require arborist constructor to be passed in for preparing git dirs

---

package.json

Bump `@npmcli/installed-package-contents` minimum version to `2.0.1` to ensure the broken `2.0.0` is not installed.
Related to: https://github.com/npm/installed-package-contents/pull/26
Fixes #231

deps: bump @npmcli/installed-package-contents

---

lib/dir.js
lib/util/npm.js
package.json
tap-snapshots/test/util/npm.js.test.cjs

This also removes any setting of `stdioString` since `true` is the
default now.

deps: @npmcli/run-script@6.0.0

---

lib/fetcher.js

fix: always ignore ownership from tar headers

---

package.json
test/registry.js

Updates `sigstore` to version 1.3.0.
This sigstore release updates the mirror URL which is used to connect to the Sigstore TUF repository. Since we're nock'ing that URL in one of the tests here, we need make an explicit version bump and update the URL in the test.

deps: sigstore@1.3.0

---

README.md
lib/fetcher.js
lib/registry.js
lib/util/cache-dir.js
test/util/cache-dir.js

Adds support for a new `tufCache` parameter that allows us to synchronize the TUF cache path with the npm CLI (see https://github.com/npm/cli/pull/6418). The TUF cache is passed to the `sigstore` library and is used when downloading the key material necessary to verify package provenance attestations.
Also updates the `cache-dir` module so that the TUF cache can be defaulted in the same way as cacache.

feat: configurable TUF cache dir

---

lib/registry.js
test/registry.js

*Context*
`npm audit signatures` performs the registry signature and sigstore attestation bundle verification in `pacote`.
The current code checks if the public key from the tuf trust root keys target has expires set to in the past:
https://github.com/npm/pacote/blob/main/lib/registry.js#L174-L175
If we decide to rotate signing keys and add expires to a old public key, verification will always fail saying the key for old packages has expired.
This means we can't rotate signing keys for npm at the moment!
*Solution*
Check public key expiry against either `integratedTime` for attestations or the publish time for registry signatures.
This allows us to rotate a key, setting expiry to after all packages that where signed with that key where published.
Complication: some really old npm packages …

fix: bug to support rotated keys in signature/attestation audit

---

lib/registry.js
package.json
test/registry.js

Update `sigstore` to version 2.2.0.
Leverages the new `tufForceCache` option in the sigstore `verify` function to make better use of the local TUF cache. Previously, the TUF cache would be refreshed with each invocation -- now the TUF cache will only be refreshed if the metadata files contained therein are expired. 
Eliminates one test case which is no longer relevant given the use of the `tufForceCache` option.

deps: bump sigstore from 2.0.0 to 2.2.0

---

lib/registry.js
test/registry.js

This was a quirk of how we were using read-package-json-fast.
Only its package.json file parsing was doing that step

fix: don't strip underscore attributes in .manifest()

---

lib/registry.js
test/registry.js

The opposite of #366. This is not a change in behavior but makes it clear that we don't expect _contentLength to be set when the request is coming directly from the registry when there is no cache.

fix: dont set _contentLength if not in headers

---

package.json

Updates `sigstore` to version 3.0.0 which removes support for node 16.

deps: bump sigstore from 2.2.0 to 3.0.0

---

lib/dir.js
tap-snapshots/test/dir.js.test.cjs
test/dir.js

Prepare script respects scriptshell config if passed matching behaviour of `npm run <script>` 
fixes: https://github.com/npm/cli/issues/7723

fix: prepare script respects scriptshell config

---

lib/dir.js
test/dir.js
test/fixtures/prepare-ignore/package.json

Adds ignoreScript option support to prevent execution of prepare lifecycle script.
from: https://github.com/npm/cli/issues/7211
part of: https://github.com/npm/statusboard/issues/898
Currently the tests don't run locally for some reason, i'm thinking because they spin up a https://localhost server. It runs in docker.
I used this to isolate the build and test locally:
```bash
docker-node() { docker run --rm -v "$(pwd)":/app -w /app -e "TAP_SNAPSHOT=$TAP_SNAPSHOT" node:22 "$@"; }
docker-node npm test
docker-node npm test -- ./test/dir.js
```

fix!: honors `ignoreScripts` option to prevent `prepare` lifecycle script

---

package.json
test/git.js

This avoids the EBUSY issue during "spawn daemon" test mentioned in https://github.com/npm/pacote/pull/408

deps: replace node builtin rmSync with rimraf

---

package.json

BREAKING CHANGE: `bun.lockb` files are now included in the strict ignore list during packing

deps!: npm-packlist@10.0.0
